[project]
name = "fun"
version = "0.0.0"
description = "some-rag-learning-project"
dependencies = [
]

[project.scripts]
fun = "fun.cli:cli"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
